FROM docker.io/nginx:latest

# Copiar el archivo confightml al directorio de Nginx
COPY ./confightml /usr/share/nginx/html/index.html

# Exponer el puerto 80 para tráfico HTTP
EXPOSE 80

# Declarar un volumen para persistir datos
VOLUME ["/mnt/nginx"]

