FROM docker.io/mysql:latest

# Exponer el puerto estándar de MySQL
EXPOSE 3306

# Declarar un volumen para persistir datos de la base de datos
VOLUME ["/mnt/mysql"]

# Configurar la contraseña de root y la base de datos inicial
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=base_de_datosInfra
